Class ispp.utils.Settings
{
/// PayPal ClientID
Parameter CLIENTID = "Aa34hRVd33prk4pURqtm6N9hkirAXIp8nPJ-5M3-msnVofgosS3OmxmUKOZVox0v3pqJXj9iWLvLkxKe";

/// PayPal Secret
Parameter SECRET = "EMIK7NLqvHYzPM69DUgeMRMyZpm0jWkwedukWlbmF3-UtbFWPg0LmoEbSHiw3klmg0-vJwQBnxr-tqsl";

/// PayPal Base Url
Parameter BASEURL = "api.sandbox.paypal.com";

/// PayPal Auth Url
Parameter AUTHURL = "/v1/oauth2/token";

/// PayPal Payment Url
Parameter PAYMENTURL = "/v1/payments/payment";

/// PayPal Port
Parameter PAYPORT = 443;

/// SSL Configuration name
Parameter SSLCONF = "PayPal";

/// Store application URL
Parameter STORURL = "http://localhost:57773";

}